import type { Metadata } from "next";
import { Geist, Geist_Mono} from "next/font/google";
import { inter } from "../components/ui/fonts";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "nextjs Project",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
         <html lang="en">
      <body className={`${inter.className} antialiased`}>{children}</body>
    </html>

    </html>
  );
}
